AWSTemplateFormatVersion: 2010-09-09
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydb
      Engine: mysql
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 5
      MasterUsername: "admin"
      MasterUserPassword: "admin1234567"
  SQLFile:
    Type: AWS::S3::Object
    Properties:
      Bucket: erplus-sql
      Key: erplus.sql
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: erplus-sql
        S3Key: lambda.zip
      Handler: index.handler
      Role: arn:aws:iam::100326269900:role/S3Role
  LambdaTrigger:
    Type: AWS::Lambda::Trigger
    Properties:
      FunctionName: my-lambda-function
      SourceArn: arn:aws:rds:eu-west-2:100326269900:db:mydb