AWSTemplateFormatVersion: 2010-09-09
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: tpchUsecase
      Engine: mysql
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 5
      MasterUsername: "admin"
      MasterUserPassword: "admin1234567"

Metadata:
  AWS::CloudFormation::Init:
    config:
      commands:
        01_import_sql:
          command: aws s3 cp s3://erplus-sql/erplus.sql /tmp/sql-file.sql && mysql -h {{resolve:secretsmanager:mydb-secret:SecretString:hostname}} -u {{resolve:secretsmanager:mydb-secret:SecretString:username}} -p{{resolve:secretsmanager:mydb-secret:SecretString:password}} < /tmp/sql-file.sql